### ISSUE TITLE
Instalar biblioteca com symfony

### ISSUE THREAD

**Issue by joaoluis89** [fredroo/openboleto#14]
Olá fredroo, fico muito feliz de ver a continuidade deste projeto e parabéns pela iniciativa!
Eu utilizava o kriansa mas o Bradesco solicitou algumas alterações que envolvem o layout do boleto (Beneficiário ao invés de Cedente e Pagador ao invés de Sacado).
Esta nova biblioteca já contempla estas alterações?
Não encontrei a referência no packgist para integração com meu projeto Symfony, essa integração é possivel?

Obrigado

**Comment by fredroo** [comment]
acredito que sim João, usa composer ? fredroo/openboleto

**Comment by joaoluis89** [comment]
Olá @fredroo tentei pelo composer e recebo a seguinte mensagem:

Problem 1
    - The requested package fredroo/openboleto could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Eu tentei procurar o packgist e não achei o repositorio lá também (Minhas configurações do composer estão setadas para aceitar dev versions).

Muito Obrigado.

**Comment by lucioabrantes** [comment]
Boa tarde,

Como o openboleto está parado, cheguei a forked, só que ao tentar instalar pelo composer, aconteceu o mesmo erro acima, conseguiu uma solução?

O projeto aqui está sendo atualizado?

**Comment by LeandroSe** [comment]
Falta arrumar o arquivo composer.json e cadastrar no packagist.

**Comment by fredroo** [comment]
Resolvido pessoal:
https://github.com/fredroo/openboleto#composer
