### ISSUE TITLE
Carteiras suportadas?

### ISSUE THREAD

**Issue by lukBarros** [fredroo/openboleto#19]

**Comment by fredroo** [comment]
qual banco? @lukBarros

**Comment by lukBarros** [comment]
BRADESCO  E CAIXA

**Comment by fredroo** [comment]
Bradesco: Linha 68
https://github.com/fredroo/openboleto/blob/master/src/OpenBoleto/Banco/Bradesco.php

Caixa: Linha 67
https://github.com/fredroo/openboleto/blob/master/src/OpenBoleto/Banco/Caixa.php
