### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by insidewill** [fredroo/openboleto#20]
Como faço para gerar um pdf? Estou com dúvidas, poderiam me dar uma luz

**Comment by fredroo** [comment]
Tem essa opção:
https://github.com/cossou/JasperPHP

E tem essa também:

https://github.com/dompdf/dompdf

**Comment by insidewill** [comment]
Obrigado!

**Comment by insidewill** [comment]
Você indica uma biblioteca para remessa 240

**Comment by fredroo** [comment]
https://github.com/QuilhaSoft/OpenCnabPHP

https://github.com/andersondanilo/CnabPHP

tenta uma dessas duas @insidewill

**Comment by insidewill** [comment]
Mais uma vez muito obrigado!
