### ISSUE TITLE
Parametrizar se mostra ou não instruções de impressão

### ISSUE THREAD

**Issue by fabioginzel** [fredroo/openboleto#34]
Criar um parâmetro que permita decidir se imprime ou não as instruções de impressão

**Comment by fabioginzel** [comment]
@Rctnet to precisando dessa funcionalidade meio urgente... tem como aceitar o pull?
abs

**Comment by Rctnet** [comment]
feito amigo

**Comment by fabioginzel** [comment]
Muito obrigado :)

**Comment by Rctnet** [comment]
não se esqueça de marcar seus bancos homologados nesta issue https://github.com/fredroo/openboleto/issues/33

**Comment by fabioginzel** [comment]
@Rctnet Eu adaptei o santander.. esta batendo com meu outro sistema mas ainda não enviei a homologação para o banco.... quer q eu já reintegre e marque ou espero o banco homologar?

**Comment by Rctnet** [comment]
Quando o banco homologar, ou quando colocar em produção, o que vier primeiro.
